api_version = "2025-07"

[[extensions]]
type = "ui_extension"
name = "Credit Limit Tile"
handle = "pos-credit-limit"
uid = "f3453e88-081b-4ef8-b8fd-e55ed6e94779"
network_access = true

[[extensions.targeting]]
module = "./src/CreditLimitTile.jsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/CreditLimitModal.jsx"
target = "pos.home.modal.render"
